# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NTA_PullUp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for NTA_PullUp
  pod 'ISHPullUp'
  pod 'google-cast-sdk', '3.2.0'
end
